### ISSUE TITLE
Incorrect comment isn't reflected by syntax colouring

### ISSUE THREAD

**Issue by drawkula** [non/tal-mode#1]
![20220227-133604](https://user-images.githubusercontent.com/9768622/155884666-6eabf6a6-f6fe-4869-974e-8449364c5c9c.png)

Is it possible to make the syntax colouring notice the bad comment ending?  Having no space before the closing `)` is one of my most frequent errors I overlook because the syntax colours look perfectly plausible while the assembler sees the rest of the file as comment.

**Comment by non** [comment]
@drawkula This is a good question.

It _is_ possible to get the bad comment rejected, but that change ends up rejecting good comments such as: `(<newline> ... )` or `( ... <newline>)` or `( )` etc.

I think maybe I'll try to make this a configuration option so people can choose which behavior they prefer. (In my case I get more annoyed by valid comments being rejected than invalid ones being accepted.)

**Comment by non** [comment]
@drawkula Please try the current version -- I've defaulted the comment highlighting to be stricter, but added a `tal-mode:strict-comments` custom setting to enable people to disable this behavior if it's incorrectly highlighting their code.
